export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const SELECT_SUPPLIER = "SELECT_SUPPLIER";
export const UPDATE_SUPPLIER = "UPDATE_SUPPLIER";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";

export const GET_CUSTOMERS = "GET_CUSTOMERS";
